### ISSUE TITLE
overworld | features for last iteration 

### ISSUE THREAD

**Issue by ScatteredDrifter** [mango-gremlin/arch-enemies#246]
## ideas and more 
- [x] finish creating passable bridges that are build automatically, basically ( #184 ) 
- WILL NOT BE WORKED ON: saving ( at best, otherwise leaving that out ) denoted in #89  #179 
- [x] indicators for some item to be found? (( should be found after all )) #257 
- [x] improve updating the bridge-state ( maybe check on more occassions )  --> this **requires a working connection** between overworld/bridge level so that one could test whether its done correctly!
- [x] fox sprite should be animated, as well as water maybe #274

- [x] (( maybe, not necessary at all )) visualization of progress for map **(ON ICE)**

- [x] NPC --> a npc should be able to have multiple quests, denoted in #256 

## Motivation

Nits and things that ought to be changed / added for proper implementation of our story and structure //

**Comment by mango-gremlin** [comment]
everything here is done, it was decided that saving would not be included for now as the game will probably be played primarily in the browser.
